image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - validate
  - format
  - terratest

validate:
  stage: validate
  script:
    - terraform --version
    - find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (terraform validate -check-variables=false "$m" && echo "√ $m") || exit 1 ; done

format:
  stage: format
  script:
    - tf=$(terraform fmt -write=false -diff); if [[ -n "$tf" ]]; then printf "$tf\n\n\nSome terraform files failed syntax validation, run 'terraform fmt' to fix\n\n"; exit 1; fi

terratest:
  image: google/cloud-sdk:alpine
  stage: terratest
  script:
    - apk update && apk upgrade
    - apk add go libc-dev terraform
    - go get github.com/gruntwork-io/terratest/modules/gcp
    - go get github.com/gruntwork-io/terratest/modules/terraform
    - cd tests
    - echo $GCLOUD_SERVICE_ACCOUNT | base64 -d > service-account.json
    - export GOOGLE_APPLICATION_CREDENTIALS=$PWD/service-account.json
    - echo $GCLOUD_SERVICE_ACCOUNT
    - cat service-account.json
    - gcloud compute regions list
    - gcloud auth activate-service-account $SERVICE_ACCOUNT_EMAIL --key-file=service-account.json
    - gcloud --quiet config set project $GOOGLE_CLOUD_PROJECT_ID
    - go test -v
    - rm service-account.json
    - cd -
